version: 2

models:
  - name: stg_stock_prices
    columns:
      - name: ticker
        tests:
          - not_null
      - name: date
        tests:
          - not_null
      - name: close
        tests:
          - not_null

  - name: stg_macro_indicators
    columns:
      - name: indicator
        tests:
          - not_null
      - name: value
        tests:
          - not_null